/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProtectedChangePasswordRouteImport } from './routes/_protected/change-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthOtpRouteImport } from './routes/_auth/otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgotPassword'
import { Route as FAQsFAQsRouteImport } from './routes/_FAQs/FAQs'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedOrdersIndexRouteImport } from './routes/_protected/orders/index'
import { Route as ProtectedCheckoutIndexRouteImport } from './routes/_protected/checkout/index'
import { Route as ProtectedOrdersOrderIdRouteImport } from './routes/_protected/orders/$orderId'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedChangePasswordRoute = ProtectedChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => AuthRoute,
} as any)
const FAQsFAQsRoute = FAQsFAQsRouteImport.update({
  id: '/_FAQs/FAQs',
  path: '/FAQs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersIndexRoute = ProtectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCheckoutIndexRoute = ProtectedCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrdersOrderIdRoute = ProtectedOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/FAQs': typeof FAQsFAQsRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/otp': typeof AuthOtpRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/change-password': typeof ProtectedChangePasswordRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/checkout': typeof ProtectedCheckoutIndexRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/FAQs': typeof FAQsFAQsRoute
  '/forgotPassword': typeof AuthForgotPasswordRoute
  '/otp': typeof AuthOtpRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/change-password': typeof ProtectedChangePasswordRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/checkout': typeof ProtectedCheckoutIndexRoute
  '/orders': typeof ProtectedOrdersIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/cart': typeof CartRoute
  '/_FAQs/FAQs': typeof FAQsFAQsRoute
  '/_auth/forgotPassword': typeof AuthForgotPasswordRoute
  '/_auth/otp': typeof AuthOtpRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/change-password': typeof ProtectedChangePasswordRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/_protected/orders/$orderId': typeof ProtectedOrdersOrderIdRoute
  '/_protected/checkout/': typeof ProtectedCheckoutIndexRoute
  '/_protected/orders/': typeof ProtectedOrdersIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/FAQs'
    | '/forgotPassword'
    | '/otp'
    | '/signin'
    | '/signup'
    | '/change-password'
    | '/products/$productId'
    | '/orders/$orderId'
    | '/checkout'
    | '/orders'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/FAQs'
    | '/forgotPassword'
    | '/otp'
    | '/signin'
    | '/signup'
    | '/change-password'
    | '/products/$productId'
    | '/orders/$orderId'
    | '/checkout'
    | '/orders'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/cart'
    | '/_FAQs/FAQs'
    | '/_auth/forgotPassword'
    | '/_auth/otp'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_protected/change-password'
    | '/products/$productId'
    | '/_protected/orders/$orderId'
    | '/_protected/checkout/'
    | '/_protected/orders/'
    | '/_protected/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CartRoute: typeof CartRoute
  FAQsFAQsRoute: typeof FAQsFAQsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/change-password': {
      id: '/_protected/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ProtectedChangePasswordRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/otp': {
      id: '/_auth/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgotPassword': {
      id: '/_auth/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_FAQs/FAQs': {
      id: '/_FAQs/FAQs'
      path: '/FAQs'
      fullPath: '/FAQs'
      preLoaderRoute: typeof FAQsFAQsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders/': {
      id: '/_protected/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ProtectedOrdersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/checkout/': {
      id: '/_protected/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ProtectedCheckoutIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/orders/$orderId': {
      id: '/_protected/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof ProtectedOrdersOrderIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedChangePasswordRoute: typeof ProtectedChangePasswordRoute
  ProtectedOrdersOrderIdRoute: typeof ProtectedOrdersOrderIdRoute
  ProtectedCheckoutIndexRoute: typeof ProtectedCheckoutIndexRoute
  ProtectedOrdersIndexRoute: typeof ProtectedOrdersIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedChangePasswordRoute: ProtectedChangePasswordRoute,
  ProtectedOrdersOrderIdRoute: ProtectedOrdersOrderIdRoute,
  ProtectedCheckoutIndexRoute: ProtectedCheckoutIndexRoute,
  ProtectedOrdersIndexRoute: ProtectedOrdersIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  CartRoute: CartRoute,
  FAQsFAQsRoute: FAQsFAQsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
